-- MySQL Script generated by MySQL Workbench
-- Sat Feb 27 20:41:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema basededatos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `basededatos` ;

-- -----------------------------------------------------
-- Schema basededatos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `basededatos` DEFAULT CHARACTER SET utf8 ;
USE `basededatos` ;

-- -----------------------------------------------------
-- Table `basededatos`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`usuario` (
  `id` INT NOT NULL,
  `tipo_identificación` VARCHAR(45) NOT NULL,
  `primer_nombre` VARCHAR(25) NOT NULL,
  `segundo_nombre` VARCHAR(25) NULL DEFAULT NULL,
  `primer_apellido` VARCHAR(25) NOT NULL,
  `segundo_apellido` VARCHAR(25) NULL DEFAULT NULL,
  `direccion` VARCHAR(85) NOT NULL,
  `email` VARCHAR(75) NULL DEFAULT NULL,
  `telefono` BIGINT(20) NOT NULL,
  `contraseña` VARCHAR(15) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `id_UNIQUE` ON `basededatos`.`usuario` (`id` ASC) ;

CREATE UNIQUE INDEX `email_UNIQUE` ON `basededatos`.`usuario` (`email` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`administrador` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Administrador_Usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `basededatos`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Administrador_Usuario1_idx` ON `basededatos`.`administrador` (`id` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`aux_cocina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`aux_cocina` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_auxCocina_Usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `basededatos`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_auxCocina_Usuario1_idx` ON `basededatos`.`aux_cocina` (`id` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`cajero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`cajero` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Cajero_Usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `basededatos`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Cajero_Usuario1_idx` ON `basededatos`.`cajero` (`id` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`cliente` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Cliente_Usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `basededatos`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Cliente_Usuario1_idx` ON `basededatos`.`cliente` (`id` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`estadopedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`estadopedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basededatos`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente` INT NOT NULL,
  `estadoPedido` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `sub_total` DOUBLE NOT NULL,
  `valor_total` DOUBLE NOT NULL,
  `tipo_pedido` VARCHAR(45) NOT NULL,
  `telefono` INT NULL DEFAULT NULL,
  `punto_entrega` VARCHAR(45) NOT NULL,
  `observaciones` VARCHAR(95) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `fk_Pedidos_Cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `basededatos`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_estadoPedido1`
    FOREIGN KEY (`estadoPedido`)
    REFERENCES `basededatos`.`estadopedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Pedidos_Cliente1_idx` ON `basededatos`.`pedido` (`cliente` ASC) ;

CREATE INDEX `fk_pedido_estadoPedido1_idx` ON `basededatos`.`pedido` (`estadoPedido` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`factura` (
  `id` INT NOT NULL,
  `pedidos` INT NOT NULL,
  `cliente` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `precio_Unitario` DOUBLE NOT NULL,
  `iva` INT NOT NULL,
  `precio_total` DOUBLE NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Factura_Pedidos1`
    FOREIGN KEY (`pedidos`)
    REFERENCES `basededatos`.`pedido` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `basededatos`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Factura_Pedidos1_idx` ON `basededatos`.`factura` (`pedidos` ASC) ;

CREATE INDEX `fk_factura_cliente1_idx` ON `basededatos`.`factura` (`cliente` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`cajero_has_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`cajero_has_factura` (
  `factura` INT NOT NULL,
  `cajero` INT NOT NULL,
  PRIMARY KEY (`Factura`, `Cajero`),
  CONSTRAINT `fk_Cajero_has_Factura_Cajero1`
    FOREIGN KEY (`Cajero`)
    REFERENCES `basededatos`.`cajero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cajero_has_Factura_Factura1`
    FOREIGN KEY (`Factura`)
    REFERENCES `basededatos`.`factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Cajero_has_Factura_Factura1_idx` ON `basededatos`.`cajero_has_factura` (`factura` ASC) ;

CREATE INDEX `fk_Cajero_has_Factura_Cajero1_idx` ON `basededatos`.`cajero_has_factura` (`cajero` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`categoria_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`categoria_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NOT NULL,
  `ruta_imagen` VARCHAR(255) NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basededatos`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria_producto` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `imagenP` LONGBLOB NULL DEFAULT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_producto_categoria_producto1`
    FOREIGN KEY (`categoria_producto`)
    REFERENCES `basededatos`.`categoria_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_producto_categoria_producto1_idx` ON `basededatos`.`producto` (`categoria_producto` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`factura_has_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`factura_has_producto` (
  `factura` INT NOT NULL,
  `producto` INT NOT NULL,
  PRIMARY KEY (`factura`, `producto`),
  CONSTRAINT `fk_factura_has_producto_factura1`
    FOREIGN KEY (`factura`)
    REFERENCES `basededatos`.`factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_has_producto_producto1`
    FOREIGN KEY (`producto`)
    REFERENCES `basededatos`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_factura_has_producto_producto1_idx` ON `basededatos`.`factura_has_producto` (`producto` ASC) ;

CREATE INDEX `fk_factura_has_producto_factura1_idx` ON `basededatos`.`factura_has_producto` (`factura` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`tipo_insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`tipo_insumo` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `basededatos`.`insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`insumo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_insumo` INT NOT NULL,
  `auxCocina` INT NOT NULL,
  `fecha_ingreso` DATETIME NOT NULL,
  `fecha_vencimiento` DATETIME NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(65) NULL DEFAULT NULL,
  `cantidad` DOUBLE NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Insumos_auxCocina1`
    FOREIGN KEY (`auxCocina`)
    REFERENCES `basededatos`.`aux_cocina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Insumos_tipo_insumo1`
    FOREIGN KEY (`tipo_insumo`)
    REFERENCES `basededatos`.`tipo_insumo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2010
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Insumos_tipo_insumo1_idx` ON `basededatos`.`insumo` (`tipo_insumo` ASC) ;

CREATE INDEX `fk_Insumos_auxCocina1_idx` ON `basededatos`.`insumo` (`auxCocina` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`insumos_del_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`insumos_del_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `insumo` INT NOT NULL,
  `producto` INT NOT NULL,
  `cantidad_insumo` DOUBLE NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Insumos_has_Productos_Insumos1`
    FOREIGN KEY (`insumo`)
    REFERENCES `basededatos`.`insumo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Insumos_has_Productos_Productos1`
    FOREIGN KEY (`producto`)
    REFERENCES `basededatos`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Insumos_has_Productos_Productos1_idx` ON `basededatos`.`insumos_del_producto` (`producto` ASC) ;

CREATE INDEX `fk_Insumos_has_Productos_Insumos1_idx` ON `basededatos`.`insumos_del_producto` (`insumo` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`proovedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`proovedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo_documento` VARCHAR(10) NOT NULL,
  `documento` BIGINT(15) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basededatos`.`insumo_has_proovedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`insumo_has_proovedor` (
  `insumo` INT NOT NULL,
  `proveedor` INT NOT NULL,
  PRIMARY KEY (`insumo`, `proveedor`),
  CONSTRAINT `fk_Insumos_has_Proovedores_Insumos1`
    FOREIGN KEY (`insumo`)
    REFERENCES `basededatos`.`insumo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Insumos_has_Proovedores_Proovedores1`
    FOREIGN KEY (`proveedor`)
    REFERENCES `basededatos`.`proovedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Insumos_has_Proovedores_Proovedores1_idx` ON `basededatos`.`insumo_has_proovedor` (`proveedor` ASC) ;

CREATE INDEX `fk_Insumos_has_Proovedores_Insumos1_idx` ON `basededatos`.`insumo_has_proovedor` (`insumo` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`metodo_de_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`metodo_de_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basededatos`.`metodo_de_pago_has_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`metodo_de_pago_has_factura` (
  `metodoDePago` INT NOT NULL,
  `factura` INT NOT NULL,
  PRIMARY KEY (`metodoDePago`, `factura`),
  CONSTRAINT `fk_Metodo de Pago_has_Factura_Factura1`
    FOREIGN KEY (`factura`)
    REFERENCES `basededatos`.`factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Metodo de Pago_has_Factura_Metodo de Pago1`
    FOREIGN KEY (`metodoDePago`)
    REFERENCES `basededatos`.`metodo_de_pago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Metodo de Pago_has_Factura_Factura1_idx` ON `basededatos`.`metodo_de_pago_has_factura` (`factura` ASC) ;

CREATE INDEX `fk_Metodo de Pago_has_Factura_Metodo de Pago1_idx` ON `basededatos`.`metodo_de_pago_has_factura` (`metodoDePago` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`operario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`operario` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Operario_Usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `basededatos`.`usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Operario_Usuario1_idx` ON `basededatos`.`operario` (`id` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`permiso` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(65) NOT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `icono` VARCHAR(150) NULL DEFAULT NULL,
  `permiso_superior_id` INT NULL DEFAULT NULL,
  `show_in_left_menu` TINYINT(4) NULL DEFAULT NULL,
  `enable` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_permiso_permiso1`
    FOREIGN KEY (`permiso_superior_id`)
    REFERENCES `basededatos`.`permiso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_permiso_permiso1_idx` ON `basededatos`.`permiso` (`permiso_superior_id` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`tipopqrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`tipopqrs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basededatos`.`estadoPqrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`estadoPqrs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basededatos`.`pqrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`pqrs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estadoPqrs` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `observaciones` VARCHAR(45) NOT NULL,
  `tipoPQRS` INT NOT NULL,
  `administrador` INT NOT NULL,
  `cliente` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_PQRS_Administrador1`
    FOREIGN KEY (`administrador`)
    REFERENCES `basededatos`.`administrador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PQRS_tipoPQRS1`
    FOREIGN KEY (`tipoPQRS`)
    REFERENCES `basededatos`.`tipopqrs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pqrs_estadoPqrs1`
    FOREIGN KEY (`estadoPqrs`)
    REFERENCES `basededatos`.`estadoPqrs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pqrs_cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `basededatos`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 106
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_PQRS_tipoPQRS1_idx` ON `basededatos`.`pqrs` (`tipoPQRS` ASC) ;

CREATE INDEX `fk_PQRS_Administrador1_idx` ON `basededatos`.`pqrs` (`administrador` ASC) ;

CREATE INDEX `fk_pqrs_estadoPqrs1_idx` ON `basededatos`.`pqrs` (`estadoPqrs` ASC) ;

CREATE INDEX `fk_pqrs_cliente1_idx` ON `basededatos`.`pqrs` (`cliente` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`detalle_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`detalle_pedido` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pedido` INT NOT NULL,
  `Producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `valor_unitario` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Productos_has_Pedidos_Pedidos1`
    FOREIGN KEY (`pedido`)
    REFERENCES `basededatos`.`pedido` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_has_Pedidos_Productos1`
    FOREIGN KEY (`Producto`)
    REFERENCES `basededatos`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Productos_has_Pedidos_Pedidos1_idx` ON `basededatos`.`detalle_pedido` (`pedido` ASC) ;

CREATE INDEX `fk_Productos_has_Pedidos_Productos1_idx` ON `basededatos`.`detalle_pedido` (`Producto` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basededatos`.`rol_has_permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`rol_has_permiso` (
  `rol` INT NOT NULL,
  `permiso` INT NOT NULL,
  PRIMARY KEY (`rol`, `permiso`),
  CONSTRAINT `fk_rol_has_permiso_permiso1`
    FOREIGN KEY (`permiso`)
    REFERENCES `basededatos`.`permiso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol_has_permiso_rol1`
    FOREIGN KEY (`rol`)
    REFERENCES `basededatos`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_rol_has_permiso_permiso1_idx` ON `basededatos`.`rol_has_permiso` (`permiso` ASC) ;

CREATE INDEX `fk_rol_has_permiso_rol1_idx` ON `basededatos`.`rol_has_permiso` (`rol` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`rol_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`rol_has_usuario` (
  `rol` INT NOT NULL DEFAULT 5,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`rol`, `usuario`),
  CONSTRAINT `fk_rol_has_usuario_rol1`
    FOREIGN KEY (`rol`)
    REFERENCES `basededatos`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol_has_usuario_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `basededatos`.`usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_rol_has_usuario_usuario1_idx` ON `basededatos`.`rol_has_usuario` (`usuario` ASC) ;

CREATE INDEX `fk_rol_has_usuario_rol1_idx` ON `basededatos`.`rol_has_usuario` (`rol` ASC) ;


-- -----------------------------------------------------
-- Table `basededatos`.`respuestaPqrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`respuestaPqrs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `respuesta` TEXT NOT NULL,
  `fecha` DATE NOT NULL,
  `pqrs` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_respuestaPqrs_pqrs1`
    FOREIGN KEY (`pqrs`)
    REFERENCES `basededatos`.`pqrs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_respuestaPqrs_pqrs1_idx` ON `basededatos`.`respuestaPqrs` (`pqrs` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
